version: '3.8'
services:
  kabind:
    image: kingasiagroup/kabind:0.98r1
    # command: tail -F /dev/null
    # command: /usr/sbin/sshd -D
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    hostname: kabind
    container_name: "kabind-1"
    privileged: true
    restart: always
    ports:
      - "22804:22"
      - "192.168.1.251:53:53/tcp"
      - "192.168.1.251:53:53/udp"
      - "192.168.1.251:953:953/tcp"
    volumes:
      - "./vol/kabind/workspace:/workspace:Z"
      - "./vol/kabind/etc/bind:/etc/bind/:Z"
      - "./vol/kabind/etc/supervisor:/etc/supervisor/:Z"
      - "./vol/kabind/root:/root/:Z"
      - "./vol/kabind/home/ccbruce:/home/ccbruce:Z"
      - "./vol/kabind/opt/:/opt/:Z"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      kamis-net:
        ipv4_address: 172.30.1.251
    logging:
      driver: json-file
      options:
        max-size: 1g

  mis-mail-server:
    container_name: mis-mail-server
    image: onlyoffice/mailserver:1.6.75
    depends_on:
      - mis-mysql
    hostname: ${MAIL_SERVER_HOSTNAME}
    environment:
       - MYSQL_SERVER=mis-mysql
       - MYSQL_SERVER_PORT=3306
       - MYSQL_ROOT_USER=mail_admin
       - MYSQL_ROOT_PASSWD=mitha35
       - MYSQL_SERVER_DB_NAME=mis-mailserver
    networks:
      kamis-net:
        ipv4_address: 172.30.1.93
    restart: always
    privileged: true
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    stdin_open: true
    tty: true
    expose:
      - '8081'
      - '3306'
    volumes:
      - ./vol/mail-server/data:/var/vmail
      - ./vol/mail-server/certs:/etc/pki/tls/mailserver
      - ./vol/mail-server/log:/var/log

  # kaad:
  #   image: kingasiagroup/kaad:0.98r6
  #   #command: tail -F /dev/null
  #   #command: /usr/sbin/sshd -D
  #   command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
  #   hostname: kaad
  #   container_name: "kaad"
  #   privileged: true
  #   restart: always
  #   ports:
  #     - "192.168.1.82:22806:22"
  #     - "192.168.1.82:53:53"
  #     - "192.168.1.82:53:53/udp"
  #     - "192.168.1.82:88:88"
  #     - "192.168.1.82:88:88/udp"
  #     - "192.168.1.82:123:123"
  #     - "192.168.1.82:135:135"
  #     - "192.168.1.82:137-138:137-138/udp"
  #     - "192.168.1.82:139:139"
  #     - "192.168.1.82:389:389"
  #     - "192.168.1.82:389:389/udp"
  #     - "192.168.1.82:445:445"
  #     - "192.168.1.82:464:464"
  #     - "192.168.1.82:464:464/udp"
  #     - "192.168.1.82:636:636"
  #     - "192.168.1.82:3268-3269:3268-3269"
  #     - "192.168.1.82:49152-49170:49152-49170"
  #   dns_search:
  #     - MIIDAI.COM
  #   dns:
  #     - 8.8.8.8
  #     - 127.0.0.1
  #   # extra_hosts:
  #   #   - dc01 dc01.ad.chaos:192.168.1.82
  #   domainname: MIIDAI.COM
  #   volumes:
  #     - "./vol/kaad/workspace:/workspace:Z"
  #     - "./vol/kaad/etc/samba:/etc/samba/:Z"
  #     - "./vol/kaad/etc/supervisor:/etc/supervisor/:Z"
  #     - "./vol/kaad/opt/:/opt/:Z"
  #     # - "./vol/kaad/opt/startup/docker-entrypoint.sh:/opt/startup/docker-entrypoint.sh"
  #     - "./vol/kaad/root:/root/:Z"
  #     - "./vol/kaad/home/ccbruce:/home/ccbruce:Z"
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - './vol/kaad/var/lib/samba/private/tls:/var/lib/samba/private/tls'
  #     - './vol/kaad/var/lib/samba/data:/var/lib/samba/'
  #     - './vol/kaad/var/lib/samba/log:/var/log/samba'
  #   networks:
  #     kamis-net:
  #       ipv4_address: 172.30.1.20
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1g
  #   environment:
  #     - TZ=Asia/Taipei
  #     - DOMAIN=MIIDAI.COM
  #     - DOMAIN_NETBIOS=MIIDAI
  #     - DOMAIN_PASS=Mithr@35#%6789
  #     - HOSTIP=${HOST_IP}
  #     - HOSTNAME=kaad
  #     - JOIN=false
  #     # - JOIN_SITE=Site0
  #     - NTPSERVERLIST=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org
  #     - FEATURE_RECYCLEBIN=true
  #     - FEATURE_KERBEROS_TGT=true
  #     - DISABLE_MD5=true
  #     - DISABLE_PWCOMPLEXITY=true
  #     - ENABLE_CUPS=false
  #     - ENABLE_DNSFORWARDER=8.8.8.8
  #     - ENABLE_DYNAMIC_PORTRANGE=49152-49170
  #     - ENABLE_INSECURELDAP=true
  #     - ENABLE_LAPS_SCHEMA=true
  #     - ENABLE_LOGS=true
  #     - ENABLE_MSCHAPV2=true
  #     - ENABLE_RFC2307=true
  #     - TLS_ENABLE=false
  #     - DEBUG_ENABLE=true
  #     - DEBUGLEVEL=1
  #     - BIND_INTERFACES_ENABLE=false
  #     - BIND_INTERFACES=eth1
  #   #cap_add:
  #   #  - NET_ADMIN
  #   #  - SYS_NICE
  #   #  - SYS_RESOURCE
  #   #  - SYS_TIME
  #   #devices:
  #   #  - /dev/net/tun
  #   #privileged: true

  # pmtools:
  #   image: kingasiagroup/kaerp:0.98
  #   #command: tail -F /dev/null
  #   #command: /usr/sbin/sshd -D
  #   command: /usr/bin/supervisord
  #   hostname: pmtools
  #   container_name: "ka-pm-tools-1"
  #   privileged: true
  #   restart: always
  #   ports:
  #     - "22826:22"
  #   volumes:
  #     - "./vol/pmtools/workspace:/workspace:Z"
  #     # - "./vol/pmtools/etc/supervisor:/etc/supervisor/:Z"
  #     - "./vol/kaerp/opt/:/opt/:Z"
  #     # - "./vol/pmtools/root:/root/:Z"
  #     # - "./vol/pmtools/home/ccbruce:/home/ccbruce:Z"
  #     # - "/etc/localtime:/etc/localtime:ro"
  #   networks:
  #     kamis-net:
  #       ipv4_address: 172.30.1.25
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1g


  cloud:
    image: kingasiagroup/kacloud:18r1
    # command: tail -F /dev/null
    # command: /usr/sbin/sshd -D
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    hostname: kacloud
    container_name: "kacloud-1"
    depends_on:
      - postgresql
    privileged: true
    restart: always
    environment:
      - HOST=mis-postgresql
      # - USER=odoo
      - PASSWORD=mithra35
      - POSTGRES_USER=odoo
    ports:
      - "22813:22"
      - "8889:80"
    volumes:
      - "./vol/kacloud/workspace:/workspace:Z"
      - "./vol/kacloud/etc/nginx:/etc/nginx/:Z"
      - "./vol/kacloud/etc/supervisor:/etc/supervisor/:Z"
      - "./vol/kacloud/root:/root/:Z"
      - "./vol/kacloud/home/ccbruce:/home/ccbruce:Z"
      - "./vol/kacloud/opt/:/opt/:Z"
      - "./vol/kacloud/var/lib/odoo:/var/lib/odoo:Z"
      - "./vol/kacloud/usr/local/etc:/usr/local/etc/:Z"
      - "./vol/kacloud/usr/local/openresty/nginx/conf:/usr/local/openresty/nginx/conf:Z"
      - "./vol/kacloud/var/www:/var/www:Z"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      kamis-net:
        ipv4_address: 172.30.1.15
    logging:
      driver: json-file
      options:
        max-size: 1g

  
  # erp:
  #   image: kingasiagroup/kaerp:17-r1
  #   # command: tail -F /dev/null
  #   # command: /usr/sbin/sshd -D
  #   # command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
  #   hostname: erp
  #   container_name: "kaerp-1"
  #   depends_on:
  #     - postgresql
  #   privileged: true
  #   restart: always
  #   environment:
  #     - HOST=mis-postgresql
  #     # - USER=odoo
  #     - PASSWORD=mithra35
  #     - POSTGRES_USER=odoo
  #   ports:
  #     - "22803:22"
  #     - "10017:8069"
  #     - "20017:8072" # live chat
  #   volumes:
  #     - "./vol/kaerp/workspace:/workspace:Z"
  #     - "./vol/kaerp/etc/supervisor:/etc/supervisor/:Z"
  #     - "./vol/kaerp/root:/root/:Z"
  #     - "./vol/kaerp/home/ccbruce:/home/ccbruce:Z"
  #     - "./vol/kaerp/opt/:/opt/:Z"
  #     - "./vol/kaerp/var/lib/odoo:/var/lib/odoo:Z"
  #     - "./vol/kaerp/etc/odoo:/etc/odoo:Z"
  #     - "./vol/kaerp/var/log/odoo:/var/log/odoo:Z"
  #     - "/etc/localtime:/etc/localtime:ro"
  #   networks:
  #     kamis-net:
  #       ipv4_address: 172.30.1.15
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1g

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:12.0.1.1748
    depends_on:
     - mis-mysql
     - mis-mail-server
     - mis-elasticsearch
     - onlyoffice-document-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=mth_640101_35
     - CONTROL_PANEL_PORT_80_TCP=80
     - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - DOCUMENT_SERVER_JWT_ENABLED=true
     - DOCUMENT_SERVER_JWT_SECRET=jwt_mithra35
     - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
     - MYSQL_SERVER_ROOT_PASSWORD=mithra35  
     - MYSQL_SERVER_DB_NAME=mis-mysql
     - MYSQL_SERVER_HOST=mis-mysql
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=mithra35
     - MAIL_SERVER_API_PORT=8081
     - MAIL_SERVER_API_HOST=mis-mail-server
     - MAIL_SERVER_DB_HOST=mis-mysql
     - MAIL_SERVER_DB_PORT=3306
     - MAIL_SERVER_DB_NAME=mis-mailserver
     - MAIL_SERVER_DB_USER=mail_admin
     - MAIL_SERVER_DB_PASS=mitha35
     - ELASTICSEARCH_SERVER_HOST=mis-elasticsearch
     - ELASTICSEARCH_SERVER_HTTPPORT=9200
    networks:
      kamis-net:
        ipv4_address: 172.30.1.91
    ports:
     - '40080:80'
     - '40443:443'
     - '45222:5222'
    stdin_open: true
    tty: true
    restart: always
    privileged: true
#    cgroup: host
    volumes:
     - ./vol/community-server/data:/var/www/onlyoffice/Data
     - ./vol/community-server/log:/var/log/onlyoffice
     - ./vol/community-server/letsencrypt:/etc/letsencrypt
     - ./vol/community-server/server_data:/var/www/onlyoffice/DocumentServerData
     - ./vol/community-server/certs:/var/www/onlyoffice/Data/certs
     - /sys/fs/cgroup:/sys/fs/cgroup:rw

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:7.1.1.23
    stdin_open: true
    tty: true
    restart: always
    environment:
     - JWT_ENABLED=true
     - JWT_SECRET=jwt_mithra35
     - JWT_HEADER=AuthorizationJwt
    networks:
      kamis-net:
        ipv4_address: 172.30.1.92
    expose:
      - '80'
      - '443'
    volumes:
       - ./vol/document-server/data:/var/www/onlyoffice/Data
       - ./vol/document-server/log:/var/log/onlyoffice
       - ./vol/document-server/fonts:/usr/share/fonts/truetype/custom
       - ./vol/document-server/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
     - onlyoffice-document-server
     - mis-mail-server
     - onlyoffice-community-server
    image: onlyoffice/controlpanel:3.1.1.467
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=mth_640101_35
    expose:
      - '80'
      - '443'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vol/onlyoffice-control-panel/data:/var/www/onlyoffice/Data
      - ./vol/onlyoffice-control-panel/log:/var/log/onlyoffice
    networks:
      kamis-net:
        ipv4_address: 172.30.1.95
    stdin_open: true
    tty: true

  redis:
    hostname: redis
    container_name: "mis-redis-1"
    image: "redis:alpine"
    environment:
      #TZ: "Asia/Shanghai"
      TZ: "Asia/Taipei"
    restart: unless-stopped
    
  postgresql:
    hostname: mis-postgresql
    user: root
    image: postgres:16
    restart: always             # run as a service
    ports:
      - "5432:5432"
    stop_signal: SIGINT
    stop_grace_period: 3s
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mithra35
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./vol/postgresql/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
      - ./vol/postgresql/initdb.d/1_db_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      kamis-net:
        ipv4_address: 172.30.1.140

  phpmyadmin:
    hostname: phpmyadmin
    container_name: "mis-phpmyadmin-1"
    image: phpmyadmin
    restart: always
    ports:
      - 15081:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=mis-mysql

  mis-mysql:
    hostname: mis-mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1 --local-infile
    # image: mariadb:10.2.40
    image: mariadb:10.6
    container_name: mis-mysql
    stop_signal: SIGINT
    stop_grace_period: 2s
    ports:
      - 13306:3306
    volumes:
      - ./vol/mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./vol/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./vol/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: mithra35
      MYSQL_DATABASE: zentao
    networks:
      kamis-net:
        ipv4_address: 172.30.1.30

  mis-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    container_name: mis-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "indices.fielddata.cache.size=30%"
      - "indices.memory.index_buffer_size=30%" 
      - "ingest.geoip.downloader.enabled=false"
    networks:
      kamis-net:
        ipv4_address: 172.30.1.205 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./vol/elasticsearch/es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"

# redis service for zentao
#  zentao-redis:
#    image: redis:3.2.12-alpine3.8
#    container_name: zentao-redis
#    networks:
#      - zentao-net

# zentao service
  # zentao:
  #   image: hub.zentao.net/app/zentao:18.9
  #   # image: hub.zentao.net/app/zentao:${TAG:-latest}
  #   container_name: zentao
  #   ports:
  #     - '18080:80'
  #   volumes:
  #     - './vol/zentao/data:/data'
  #   depends_on:
  #     - database
  #   environment:
  #     - ZT_MYSQL_HOST=mis-mysql
  #     - ZT_MYSQL_PORT=3306
  #     - ZT_MYSQL_USER=root
  #     - ZT_MYSQL_PASSWORD=mithra35
  #     - ZT_MYSQL_DB=zentao
  #    # - PHP_SESSION_TYPE=redis
  #    # - PHP_SESSION_PATH=tcp://zentao-redis:6379
  #    # - PHP_REDIS_SENTINEL=1  
  #     - PHP_MAX_EXECUTION_TIME=120
  #     - PHP_MAX_INPUT_VARS=2000
  #     - PHP_MEMORY_LIMIT=512M
  #     - PHP_POST_MAX_SIZE=128M
  #     - PHP_UPLOAD_MAX_FILESIZE=128M
  #     - LDAP_ENABLED=false
  #     - SMTP_ENABLED=false
  #     - SMTP_FROMNAME=PM
  #     - SMTP_HOST=192.168.50.182
  #     - SMTP_PORT=25
  #     - SMTP_USER=root@demo.com
  #     - SMTP_PASS=password
  #     - APP_DEFAULT_PORT=80
  #     - APP_DOMAIN=zentao.demo.com
  #     - PROTOCOL_TYPE=http
  #     - EASYSOFT_DEBUG=true
  #     - DEBUG=1
  #     - IS_CONTAINER=true
  #     - LINK_GIT=false
  #     - GIT_TYPE=gitea
  #     - GIT_INSTANCE_NAME=demo
  #     - GIT_USERNAME=user
  #     - GIT_PASSWORD=password
  #     - GIT_DOMAIN=https://git.demo.com
  #     # - GIT_TOKEN=token-example
  #     - LINK_CI=false
  #     - CI_TYPE=jenkins
  #     - CI_URL=https://jenkins.demo.com
  #     - CI_USERNAME=user
  #     - CI_PASSWORD=password
  #     # - CI_TOKEN=token-example
  #     - LINK_SCAN=false
  #     - SCAN_TYPE=sonarqube
  #     - SCAN_URL=https://sonarqube.demo.com
  #     - SCAN_USERNAME=user
  #     - SCAN_PASSWORD=password
  #   networks:
  #     kamis-net:
  #       ipv4_address: 172.30.1.35

    # certbot:
    #     container_name: certbot
    #     image: certbot/certbot:latest
    #     # command: certonly --webroot --webroot-path=/var/www/html -- email ccbruce@kingasiagroup.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
    #     volumes:
    #         - ./vol/certbot/conf:/etc/letsencrypt
    #         - ./vol/certbot/logs:/var/log/letsencrypt
    #         - ./vol/certbot/data:/var/www/html
networks:
  kamis-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
