version: '3.7'

networks:
  samba-net:
    name: samba-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.101.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_samba

services:
  samba:
    build: .
    container_name: samba-dc01
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - './samba-dc01/tls:/var/lib/samba/private/tls'
      - './samba-dc01/data:/var/lib/samba/'
      - './samba-dc01/log:/var/log/samba'
    environment:
      - TZ=Europe/Berlin
      - DOMAIN=SAM.DOM
      - DOMAIN_NETBIOS=WORKGROUP
      - DOMAIN_PASS=Pa11w0rd!
#      - HOSTIP=${HOST_IP}
      - HOSTNAME=dc01
      - JOIN=false
#      - JOIN_SITE=Site0
      - NTPSERVERLIST=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org
      - FEATURE_RECYCLEBIN=true
      - FEATURE_KERBEROS_TGT=true
      - DISABLE_MD5=true
      - DISABLE_PWCOMPLEXITY=true
      - ENABLE_CUPS=false
      - ENABLE_DNSFORWARDER=8.8.8.8
      - ENABLE_DYNAMIC_PORTRANGE=49152-49170
      - ENABLE_INSECURELDAP=true
      - ENABLE_LAPS_SCHEMA=true
      - ENABLE_LOGS=true
      - ENABLE_MSCHAPV2=true
      - ENABLE_RFC2307=true
      - TLS_ENABLE=false
      - DEBUG_ENABLE=true
      - DEBUGLEVEL=1
      - BIND_INTERFACES_ENABLE=false
      - BIND_INTERFACES=eth1
    networks:
      samba-net:
        ipv4_address: 172.101.1.100
#    ports:
#      - 53:53
#      - 53:53/udp
#      - 88:88
#      - 88:88/udp
#      - 123:123
#      - 135:135
#      - 137-138:137-138/udp
#      - 139:139
#      - 389:389
#      - 389:389/udp
#      - 445:445
#      - 464:464
#      - 464:464/udp
#      - 636:636
#      - 3268-3269:3268-3269
#      - 49152-49170:49152-49170
    dns_search:
      - SAM.DOM
    dns:
      - 127.0.0.1
#    extra_hosts:
#      - dc01 dc01.ad.chaos:192.168.1.45
    hostname: dockersamba01
    domainname: SAM.DOM
#    cap_add:
#      - NET_ADMIN
#      - SYS_NICE
#      - SYS_RESOURCE
#      - SYS_TIME
#    devices:
#      - /dev/net/tun
    privileged: true

  samba-join:
    build: .
    container_name: samba-dc02
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - './samba-dc02/tls:/var/lib/samba/private/tls'
      - './samba-dc02/data:/var/lib/samba/'
      - './samba-dc02/log:/var/log/samba'
    environment:
      - TZ=Europe/Berlin
      - DOMAIN=SAM.DOM
      - DOMAIN_NETBIOS=WORKGROUP
      - DOMAIN_PASS=Pa11w0rd!
#      - HOSTNAME=dc02
      - JOIN=true
#      - JOIN_SITE=Site1
      - NTPSERVERLIST=172.101.1.100
      - DISABLE_MD5=true
#      - ENABLE_CUPS=false
      - ENABLE_DNSFORWARDER=172.101.1.100
      - ENABLE_DYNAMIC_PORTRANGE=49152-49170
      - ENABLE_INSECURELDAP=false
      - ENABLE_LOGS=false
      - ENABLE_MSCHAPV2=true
      - TLS_ENABLE=false
      - DEBUG_ENABLE=true
      - DEBUGLEVEL=1
      - BIND_INTERFACES_ENABLE=false
      - BIND_INTERFACES=eth1
    networks:
      samba-net:
        ipv4_address: 172.101.2.200
#    ports:
#      - 53:53
#      - 53:53/udp
#      - 88:88
#      - 88:88/udp
#      - 123:123
#      - 135:135
#      - 137-138:137-138/udp
#      - 139:139
#      - 389:389
#      - 389:389/udp
#      - 445:445
#      - 464:464
#      - 464:464/udp
#      - 636:636
#      - 3268-3269:3268-3269
#      - 49152-49170:49152-49170
    dns_search:
      - SAM.DOM
    dns:
      - 127.0.0.1
      - 172.101.1.100
#    extra_hosts:
#      - dc01 dc01.ad.chaos:192.168.1.45
    hostname: dockersamba02
    domainname: SAM.DOM
#    cap_add:
#      - NET_ADMIN
#      - SYS_NICE
#      - SYS_RESOURCE
#      - SYS_TIME
#    devices:
#      - /dev/net/tun
    privileged: true

# git clone https://github.com/Netgear/wsdd2
#  wsdd2:
#    build:
#      context: ./wsdd2
#    container_name: wsdd2
#    environment:
#      - HOSTNAME=blabla
#      - WORKGROUP=WORKGROUP
#    network_mode: "host"
#    privileged: true
#    healthcheck:
#      interval: "30s"
#      timeout: "10s"
#      test: pgrep -x "/usr/sbin/wsdd2" || exit 1
